# Generated by Django 5.2.1 on 2025-05-31 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="account_balance",
            new_name="wallet_balance",
        ),
    ]
