# Generated by Django 5.2.1 on 2025-06-02 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0003_alter_purchase_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchase',
            name='created_at',
        ),
    ]
