# Generated by Django 5.2.1 on 2025-06-04 10:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pastquestions', '0007_remove_pastquestion_uploaded_at'),
        ('purchase', '0004_remove_purchase_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase', to='pastquestions.pastquestion'),
        ),
    ]
