# Generated by Django 5.2.1 on 2025-05-30 15:29

import cloudinary.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PastQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('description', models.TextField(max_length=10000)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('file_url', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True)),
                ('subject', models.CharField(max_length=100)),
                ('level', models.CharField(max_length=50)),
                ('exam_type', models.CharField(max_length=500)),
                ('year', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_questions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
