# Generated by Django 5.2.1 on 2025-05-30 17:01

import cloudinary.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pastquestions', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pastquestion',
            name='file_url',
        ),
        migrations.CreateModel(
            name='PastQuestionFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_url', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('past_question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='pastquestions.pastquestion')),
            ],
        ),
    ]
