# Generated by Django 5.2.1 on 2025-05-31 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pastquestions", "0002_remove_pastquestion_file_url_pastquestionfile"),
    ]

    operations = [
        migrations.AddField(
            model_name="pastquestion",
            name="download_url",
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
