# Generated by Django 5.2.1 on 2025-06-01 17:55

import cloudinary.models
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pastquestions', '0003_pastquestion_download_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='pastquestion',
            name='file_url',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='pastquestion',
            name='uploaded_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.DeleteModel(
            name='PastQuestionFile',
        ),
    ]
