# Generated by Django 5.2.1 on 2025-06-01 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pastquestions', '0004_pastquestion_file_url_pastquestion_uploaded_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pastquestion',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
