# Generated by Django 5.2.1 on 2025-06-01 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pastquestions', '0005_alter_pastquestion_uploaded_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pastquestion',
            name='download_url',
        ),
    ]
